apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"cora-agent","part-of":"cora-demo"},"name":"cora-agent","namespace":"natwest"},"spec":{"ports":[{"name":"http","port":8080,"targetPort":8080}],"selector":{"app":"cora-agent"}}}
  creationTimestamp: "2026-08-27T13:56:13Z"
  labels:
    app: cora-agent
    part-of: cora-demo
  name: cora-agent
  namespace: natwest
  resourceVersion: "9143926"
  uid: fac78e3a-77e9-441b-afea-b4b349a4db87
spec:
  clusterIP: 10.100.165.165
  clusterIPs:
  - 10.100.165.165
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cora-agent
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
