apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"cora-otelcol","part-of":"cora-demo"},"name":"cora-otelcol","namespace":"natwest"},"spec":{"ports":[{"name":"otlp-grpc","port":4317,"targetPort":4317},{"name":"otlp-http","port":4318,"targetPort":4318}],"selector":{"app":"cora-otelcol"}}}
  creationTimestamp: "2026-08-28T08:57:53Z"
  labels:
    app: cora-otelcol
    part-of: cora-demo
  name: cora-otelcol
  namespace: natwest
  resourceVersion: "9346385"
  uid: ba5947df-9a01-4840-9a28-0ee12d840e43
spec:
  clusterIP: 10.100.21.105
  clusterIPs:
  - 10.100.21.105
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app: cora-otelcol
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
