{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: natwest-payments
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: false
{{- end }}
