#!/usr/bin/env bash
# Recreate the ITSI "AI agents" service (3 KPIs + entity type + entity)
# from the ground up, via the itoa_interface REST API.
#
# Usage:  source ../config/kit.env && ./create_ai_agents_service.sh <root-service-key>
#   <root-service-key> = _key of the service-tree root to hang "AI agents"
#   under (in the original build: nwpay_l1). Omit to create it unparented.
#
# Everything is additive; nothing existing is modified.
set -euo pipefail
HOST="https://${SPLUNK_ENTERPRISE_HOST}:8089"
AUTH="${SPLUNK_ENTERPRISE_ADMIN_USER}:${SPLUNK_ENTERPRISE_ADMIN_PASSWORD}"
API="servicesNS/nobody/SA-ITOA/itoa_interface"
ROOT_KEY="${1:-}"
AGENT="${CORA_AGENT_NAME:-Cora}"
IDX="${SPLUNK_HEC_INDEX:-nwpay_audit}"
uuid() { python3 -c "import uuid;print(uuid.uuid4().hex[:20])"; }

# Base search fragments (the agent logs one HEC event per question:
#   action=cora_ask, agent=<AGENT>, hallucinated=true|false, cost_usd=N)
BASE="index=${IDX} sourcetype=\"nwpay:cora\" source=\"cora-agent\" | spath | search action=cora_ask"

kpi() { # title, key, search_suffix, threshold_csv "info,low,med,high,crit-ish", unit
  local TITLE="$1" KEY="$2" SUFFIX="$3" T="$4" UNIT="$5"
  python3 - "$TITLE" "$KEY" "$SUFFIX" "$T" "$UNIT" <<'PYEOF'
import json, sys
title, key, suffix, t, unit = sys.argv[1:6]
lo, med, hi = [float(x) for x in t.split(',')]
print(json.dumps({
  "_key": key, "title": title, "unit": unit,
  "search_type": "adhoc",
  "base_search": suffix,
  "is_service_entity_filter": False,
  "is_entity_breakdown": True,
  "entity_breakdown_id_fields": "agent",
  "entity_id_fields": "agent",
  "entity_statop": "sum",
  "search_alert_earliest": "5",          # 5-MINUTE aggregation window: thresholds are per-5min!
  "alert_period": "1",
  "fill_gaps": "custom_value", "custom_threshold_value": 0, "gap_custom_alert_value": "0",
  "aggregate_statop": "sum", "threshold_field": "count",
  "aggregate_thresholds": {
    "isMaxStatic": False, "renderBoundaryMax": hi*2, "renderBoundaryMin": 0,
    "baseSeverityLabel": "normal", "baseSeverityValue": 2, "baseSeverityColor": "#99D18B", "baseSeverityColorLight": "#DCEFD7",
    "gaugeMax": hi*2, "gaugeMin": 0, "metricField": "count", "isMinStatic": True, "search": "",
    "thresholdLevels": [
      {"severityLabel":"medium","severityValue":4,"dynamicParam":0,"severityColor":"#FCB64E","severityColorLight":"#FEE6C1","thresholdValue":lo},
      {"severityLabel":"high","severityValue":5,"dynamicParam":0,"severityColor":"#F26A35","severityColorLight":"#FBCBB9","thresholdValue":med},
      {"severityLabel":"critical","severityValue":6,"dynamicParam":0,"severityColor":"#B50101","severityColorLight":"#E5A6A6","thresholdValue":hi},
    ]}
}))
PYEOF
}

echo ">> creating service 'AI agents'"
SVC_KEY=$(python3 - "$ROOT_KEY" "$AGENT" "$BASE" <<'PYEOF'
import json, sys, uuid
root, agent, base = sys.argv[1], sys.argv[2], sys.argv[3]
def kpi_key(): return "cora_" + uuid.uuid4().hex[:20]
svc = {
  "title": "AI agents",
  "description": f"AI assistant ({agent}) request rate / hallucinations / cost. Generated by nwg-cora-kit.",
  "enabled": 1,
  "services_depends_on": [],
}
print(json.dumps(svc))
PYEOF
)
SVC_RESP=$(curl -sk -u "$AUTH" -X POST -H 'Content-Type: application/json' -d "$SVC_KEY" "$HOST/$API/service")
SVC_ID=$(echo "$SVC_RESP" | python3 -c "import json,sys;print(json.load(sys.stdin)['_key'])")
echo "   service _key = $SVC_ID"

echo ">> adding 3 KPIs (client-supplied _key REQUIRED by the API)"
# Pull, append KPIs, push back (ITSI wants full-object updates)
curl -sk -u "$AUTH" "$HOST/$API/service/$SVC_ID" -o /tmp/svc.json
python3 - "$SVC_ID" "$AGENT" "$BASE" <<'PYEOF'
import json, sys, uuid
svc_id, agent, base = sys.argv[1:4]
svc = json.load(open('/tmp/svc.json'))
def mk(title, search, thresholds, unit):
    lo, med, hi = thresholds
    return {
      "_key": "cora_" + uuid.uuid4().hex[:20], "title": title, "unit": unit,
      "search_type": "adhoc", "adhoc_search": search, "threshold_field": "count",
      "aggregate_statop": "sum", "entity_statop": "sum",
      "is_entity_breakdown": True, "entity_breakdown_id_fields": "agent",
      "entity_id_fields": "agent", "is_service_entity_filter": False,
      "search_alert_earliest": "5", "alert_period": "1",
      "fill_gaps": "custom_value", "gap_custom_alert_value": "0",
      "aggregate_thresholds": {
        "isMaxStatic": False, "renderBoundaryMax": hi*2, "renderBoundaryMin": 0,
        "baseSeverityLabel": "normal", "baseSeverityValue": 2,
        "baseSeverityColor": "#99D18B", "baseSeverityColorLight": "#DCEFD7",
        "gaugeMax": hi*2, "gaugeMin": 0, "metricField": "count", "isMinStatic": True, "search": "",
        "thresholdLevels": [
          {"severityLabel":"medium","severityValue":4,"dynamicParam":0,"severityColor":"#FCB64E","severityColorLight":"#FEE6C1","thresholdValue":lo},
          {"severityLabel":"high","severityValue":5,"dynamicParam":0,"severityColor":"#F26A35","severityColorLight":"#FBCBB9","thresholdValue":med},
          {"severityLabel":"critical","severityValue":6,"dynamicParam":0,"severityColor":"#B50101","severityColorLight":"#E5A6A6","thresholdValue":hi},
        ]},
    }
# thresholds are per-5-minute sums (search_alert_earliest=5): DO NOT use per-minute values
kpis = [
  mk("AI Request Rate",        f"{base} | stats count",                                   (25, 40, 75),      "req/5min"),
  mk("AI Hallucination Count", f"{base} hallucinated=true | stats count",                  (1, 3, 6),         "hallucinations/5min"),
  mk("AI Cost USD",            f"{base} | stats sum(cost_usd) as count",                   (0.015, 0.025, 0.05), "USD/5min"),
]
svc.setdefault('kpis', [k for k in svc.get('kpis', [])])
svc['kpis'].extend(kpis)
json.dump(svc, open('/tmp/svc.json','w'))
print('   appended', len(kpis), 'KPIs')
PYEOF
curl -sk -u "$AUTH" -X POST -H 'Content-Type: application/json' --data-binary @/tmp/svc.json "$HOST/$API/service/$SVC_ID" >/dev/null
echo "   KPIs pushed"

echo ">> entity type 'AI Agent' (+ O11y drilldowns) and entity '$AGENT'"
python3 - "$AGENT" <<PYEOF
import json
agent = "$AGENT"
realm = "${SPLUNK_REALM}"
et = {
  "_key": "nwpay_et_aiagent", "title": "AI Agent",
  "description": "AI assistant entities (nwg-cora-kit)",
  "dashboard_drilldowns": [
    {"title": "AI Agent Monitoring (Observability Cloud)", "dashboard_type": "navigation_link",
     "base_url": f"https://app.{realm}.signalfx.com/#/ai-monitoring/agents?endTime=Now&startTime=-8d", "params": {"static_filters": {}, "alias_filters": []}},
    {"title": "AI cost & usage dashboard", "dashboard_type": "navigation_link",
     "base_url": f"https://app.{realm}.signalfx.com/#/dashboards", "params": {"static_filters": {}, "alias_filters": []}},
  ],
  "vital_metrics": [],
}
json.dump(et, open('/tmp/et.json','w'))
ent = {
  "title": agent.lower(),
  "identifier": {"fields": ["aiagent", "agent"], "values": [agent.lower(), agent]},
  "informational": {"fields": ["provider", "model"], "values": ["anthropic", "${CORA_MODEL}"]},
  "entity_type_ids": ["nwpay_et_aiagent"],
}
json.dump(ent, open('/tmp/ent.json','w'))
PYEOF
curl -sk -u "$AUTH" -X POST -H 'Content-Type: application/json' --data-binary @/tmp/et.json  "$HOST/$API/entity_type" >/dev/null && echo "   entity type created"
curl -sk -u "$AUTH" -X POST -H 'Content-Type: application/json' --data-binary @/tmp/ent.json "$HOST/$API/entity" >/dev/null && echo "   entity created"

cat <<NOTE

DONE. Manual follow-ups in the ITSI UI (or extend this script):
  1. Add an entity rule on 'AI agents' matching alias aiagent=$(echo "$AGENT" | tr 'A-Z' 'a-z') (case matters for agent=$AGENT).
  2. If you passed a root key, add 'AI agents' to that service's dependents.
  3. Update the second drilldown's base_url to your recreated dashboard id.
NOTE
