#!/usr/bin/env bash
# scripts/05b-frontend-public-proxy.sh
#
# Stands up an nginx reverse proxy on the existing Splunk Enterprise EC2
# instance so the in-cluster web-frontend SPA is reachable on a public URL
# (port 80). Required because the AWS Organization SCP on this account
# explicitly denies `elasticloadbalancing:CreateLoadBalancer`, which would
# otherwise be the natural way to surface a `type: LoadBalancer` Service.
#
# What it does:
#   1. Reads the Splunk EC2 public IP from terraform output.
#   2. Discovers EKS worker-node *private* IPs from kubectl (the workers
#      sit in the same default VPC as the Splunk EC2, so private routing
#      is the right hop).
#   3. SSHes into the EC2, installs nginx if missing, renders an upstream
#      that round-robins across the worker IPs to the web-frontend
#      NodePort (30598) and the api-gateway NodePort (30680), and reloads
#      nginx atomically (nginx -t before -s reload).
#   4. Verifies the public URL with `curl -fsS -o /dev/null` so we fail
#      loudly if the SG path is mis-set.
#
# Re-run this whenever the EKS managed node group rolls (the script does
# the rendering server-side from the live `kubectl get nodes` output, so
# re-running picks up the new IPs).
#
# Required env vars: none (terraform + kubectl + ssh keys discovered).
# Optional env vars:
#   WEB_FRONTEND_NODE_PORT   default 30598 (must match values.yaml)
#   API_GATEWAY_NODE_PORT    default 30680 (must match values.yaml)
#   SPLUNK_PEM               default ${TERRAFORM_DIR}/splunk-enterprise.pem
#   SPLUNK_USER              default ec2-user
#   PROXY_LOG_DIR            default /var/log/nginx (on the EC2)
#   SKIP_VERIFY=1            skip the curl smoke test at the end

set -Eeuo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib.sh"

require_cmd kubectl terraform ssh scp

WEB_FRONTEND_NODE_PORT="${WEB_FRONTEND_NODE_PORT:-30598}"
API_GATEWAY_NODE_PORT="${API_GATEWAY_NODE_PORT:-30680}"
SPLUNK_PEM="${SPLUNK_PEM:-${TERRAFORM_DIR}/splunk-enterprise.pem}"
SPLUNK_USER="${SPLUNK_USER:-ec2-user}"
PROXY_LOG_DIR="${PROXY_LOG_DIR:-/var/log/nginx}"
NS="${NS:-${SERVICE_NAMESPACE}}"

# --- 1. Read the Splunk EC2 public IP from terraform -------------------------
# tf_output (from lib.sh) calls `terraform output -raw`. If the value is null
# (splunk_enterprise_enabled=false) terraform prints the literal `null`, so
# guard against that.
SPLUNK_PUBLIC_IP="$(tf_output splunk_enterprise_public_ip 2>/dev/null || true)"
if [[ -z "${SPLUNK_PUBLIC_IP}" || "${SPLUNK_PUBLIC_IP}" == "null" ]]; then
  fail "splunk_enterprise_public_ip is empty/null. Is var.splunk_enterprise_enabled=true and terraform applied?"
fi

SPLUNK_PEM="$(ensure_splunk_ssh_key "${SPLUNK_PEM}")"
# Defensive chmod: ssh refuses keys with permissive perms.
chmod 600 "${SPLUNK_PEM}" 2>/dev/null || true

log "Splunk EC2 public IP:      ${SPLUNK_PUBLIC_IP}"
log "web-frontend NodePort:     ${WEB_FRONTEND_NODE_PORT}"
log "api-gateway   NodePort:    ${API_GATEWAY_NODE_PORT}"

# --- 2. Discover EKS worker private IPs --------------------------------------
# Filter to nodes that carry the natwest-payments workload label so we don't
# accidentally route traffic to the (currently non-existent) addon node group.
# Field selector type=InternalIP returns the node's *private* address, which
# is what the in-VPC Splunk EC2 should hop to.
#
# We use `while read` instead of bash 4+ `mapfile` so this stays portable to
# the macOS-bundled bash 3.2.
WORKER_IPS=()
while IFS= read -r ip; do
  [[ -n "${ip}" ]] && WORKER_IPS+=("${ip}")
done < <(kubectl get nodes \
  -l workload=natwest-payments-demo \
  -o jsonpath='{range .items[?(@.status.conditions[-1].type=="Ready")]}{.status.addresses[?(@.type=="InternalIP")].address}{"\n"}{end}' \
  | grep -E '^[0-9]+(\.[0-9]+){3}$' || true)

if [[ ${#WORKER_IPS[@]} -eq 0 ]]; then
  fail "No Ready EKS worker nodes found. Has the cluster scaled to zero?"
fi

log "discovered ${#WORKER_IPS[@]} worker IP(s): ${WORKER_IPS[*]}"

# --- 3. Render the nginx config locally, then ship it ------------------------
# We render server-side onto a tmpfile and then `mv` it into place to make
# the swap atomic. `nginx -t` validates the new config before reload so a
# typo can never leave the proxy in a broken state.
TMP_CONF="$(mktemp -t spa-nginx.conf.XXXXXX)"
trap 'rm -f "${TMP_CONF}"' EXIT

# Build the upstream block
UPSTREAM_FRONTEND_BODY=""
UPSTREAM_GATEWAY_BODY=""
for ip in "${WORKER_IPS[@]}"; do
  UPSTREAM_FRONTEND_BODY+="    server ${ip}:${WEB_FRONTEND_NODE_PORT} max_fails=2 fail_timeout=10s;"$'\n'
  UPSTREAM_GATEWAY_BODY+="    server ${ip}:${API_GATEWAY_NODE_PORT} max_fails=2 fail_timeout=10s;"$'\n'
done

cat >"${TMP_CONF}" <<EOF
# Generated by scripts/05b-frontend-public-proxy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do not hand-edit: rerun the script to refresh upstream IPs after a node-group roll.

upstream natwest_web_frontend {
${UPSTREAM_FRONTEND_BODY}    keepalive 32;
}

upstream natwest_api_gateway {
${UPSTREAM_GATEWAY_BODY}    keepalive 32;
}

# JSON access log for the public SPA proxy. Mirrors the in-cluster
# web-frontend log format (see frontend/nginx/log_format.conf) so a
# downstream Splunk index parses both with the same props.conf stanza
# (sourcetype=nginx:access, index=nwpay_infra). escape=json prevents
# log-injection via embedded CRLF/quotes (codeguard-0-logging).
log_format spa_proxy_json escape=json
  '{'
    '"@timestamp":"\$time_iso8601",'
    '"time_local":"\$time_local",'
    '"remote_addr":"\$remote_addr",'
    '"x_forwarded_for":"\$http_x_forwarded_for",'
    '"http_host":"\$host",'
    '"request_method":"\$request_method",'
    '"request_uri":"\$request_uri",'
    '"server_protocol":"\$server_protocol",'
    '"status":\$status,'
    '"body_bytes_sent":\$body_bytes_sent,'
    '"request_time":\$request_time,'
    '"upstream_addr":"\$upstream_addr",'
    '"upstream_status":"\$upstream_status",'
    '"upstream_response_time":"\$upstream_response_time",'
    '"upstream_connect_time":"\$upstream_connect_time",'
    '"http_referer":"\$http_referer",'
    '"http_user_agent":"\$http_user_agent",'
    '"request_id":"\$request_id"'
  '}';

server {
    listen 80 default_server;
    server_name _;
    access_log ${PROXY_LOG_DIR}/spa-access.log spa_proxy_json;
    error_log  ${PROXY_LOG_DIR}/spa-error.log warn;

    # Tight defaults; the SPA is fully client-rendered so requests are short-
    # lived. Long enough that /process can complete (api-gateway is the slow
    # path, ~6s on tail-latency injections).
    proxy_connect_timeout 5s;
    proxy_send_timeout    10s;
    proxy_read_timeout    30s;

    # Forwarded headers so the api-gateway sees the original client IP /
    # scheme. Useful for RUM/APM correlation.
    proxy_set_header Host              \$host;
    proxy_set_header X-Real-IP         \$remote_addr;
    proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-Host  \$host;
    proxy_http_version 1.1;
    proxy_set_header Connection "";

    # /api/* -> api-gateway NodePort. Strip the /api prefix so the gateway
    # sees the same path it would in-cluster.
    location /api/ {
        rewrite ^/api/(.*)\$ /\$1 break;
        proxy_pass http://natwest_api_gateway;
    }

    # Health endpoint that bypasses the upstream so launchd/curl probes can
    # confirm nginx itself is alive even when the cluster is rolling.
    location = /__proxy_health {
        access_log off;
        default_type text/plain;
        return 200 "ok\n";
    }

    # Everything else -> web-frontend NodePort (which serves the React bundle
    # and also handles its own /api/* fallback for in-cluster RUM hits).
    location / {
        proxy_pass http://natwest_web_frontend;
    }
}
EOF

# --- 4. Push and reload on the EC2 -----------------------------------------
# Quiet but verbose-on-error: we emit every remote command via `set -x` inside
# the heredoc so a bad install/reload prints the offending line.

REMOTE_TMP="/tmp/spa-nginx.conf.\$\$"
SSH_OPTS=(
  -i "${SPLUNK_PEM}"
  -o StrictHostKeyChecking=no       # first-time connect; alternative is to populate ~/.ssh/known_hosts
  -o UserKnownHostsFile=/dev/null
  -o ConnectTimeout=10
  -o ServerAliveInterval=15
)

log "scp config -> ${SPLUNK_USER}@${SPLUNK_PUBLIC_IP}:${REMOTE_TMP}"
# shellcheck disable=SC2029  # remote shell expansion of $$ is intentional below
scp "${SSH_OPTS[@]}" "${TMP_CONF}" "${SPLUNK_USER}@${SPLUNK_PUBLIC_IP}:/tmp/spa-nginx.conf.staging"

log "ssh -> install/refresh nginx + watchdog"
ssh "${SSH_OPTS[@]}" "${SPLUNK_USER}@${SPLUNK_PUBLIC_IP}" 'bash -se' <<'REMOTE'
set -Eeuo pipefail
set -x

# Idempotent install. AL2023 ships dnf; nginx is in amazonlinux-extras by default.
if ! command -v nginx >/dev/null 2>&1; then
  sudo dnf install -y nginx
fi

# AL2023's stock nginx.conf already includes /etc/nginx/conf.d/*.conf and
# defines its own port-80 server in the default `server { ... }` block of
# nginx.conf. Disable that default by trimming the include glob *if* present;
# otherwise nginx -t will refuse the new conflicting `listen 80 default_server`.
DEFAULT_CONF=/etc/nginx/conf.d/default.conf
if [[ -f "${DEFAULT_CONF}" ]]; then
  sudo mv "${DEFAULT_CONF}" "${DEFAULT_CONF}.bak.$(date -u +%Y%m%d%H%M%S)"
fi

# Atomic swap into place. `mv` on the same filesystem is atomic so a half-
# written conf is impossible.
sudo mv /tmp/spa-nginx.conf.staging /etc/nginx/conf.d/spa.conf
sudo chown root:root /etc/nginx/conf.d/spa.conf
sudo chmod 0644 /etc/nginx/conf.d/spa.conf

# Validate before applying. nginx -t exits non-zero on config errors and
# leaves the running config untouched.
sudo nginx -t

# enable + restart on first boot, reload thereafter
if ! systemctl is-active --quiet nginx; then
  sudo systemctl enable --now nginx
else
  sudo systemctl reload nginx
fi

# -- watchdog --------------------------------------------------------------
# A 30 s systemd timer drives a oneshot service that curl-probes
# /__proxy_health on localhost. Two consecutive failures (state file in
# /var/run) restart nginx and emit a stderr line that journald captures
# under unit=natwest-spa-watchdog.service. The single-failure tolerance
# avoids a transient TCP blip flapping the proxy.
#
# Idempotent: rendered fresh from this heredoc on every run so a future
# tweak to the probe interval or restart threshold only needs a re-run of
# scripts/05b-frontend-public-proxy.sh.
sudo tee /usr/local/bin/natwest-spa-watchdog.sh >/dev/null <<'SCRIPT'
#!/usr/bin/env bash
# Probe nginx /__proxy_health. After two consecutive failures, restart
# nginx so the SPA public URL recovers without operator intervention.
# Designed to be run by systemd; never exits non-zero so the timer doesn't
# fall into the failed state.
set -u
STATE=/var/run/natwest-spa-watchdog.fail-count
THRESHOLD=2

# Curl with strict timeouts. -fS exits non-zero on HTTP >= 400 and prints
# a one-line error message; --max-time 4 caps total wall time so the
# timer's RuntimeMaxSec=15 is never breached.
if curl -fsS -m 4 http://127.0.0.1/__proxy_health >/dev/null 2>&1; then
  : >"${STATE}"
  exit 0
fi

count=0
[[ -s "${STATE}" ]] && count="$(cat "${STATE}" 2>/dev/null || echo 0)"
count=$((count + 1))
printf '%d\n' "${count}" >"${STATE}"

echo "natwest-spa-watchdog: /__proxy_health failed (count=${count}/${THRESHOLD})" >&2

if [[ "${count}" -ge "${THRESHOLD}" ]]; then
  echo "natwest-spa-watchdog: threshold reached, restarting nginx" >&2
  systemctl restart nginx || true
  : >"${STATE}"
fi
exit 0
SCRIPT
sudo chown root:root /usr/local/bin/natwest-spa-watchdog.sh
sudo chmod 0755 /usr/local/bin/natwest-spa-watchdog.sh

sudo tee /etc/systemd/system/natwest-spa-watchdog.service >/dev/null <<'UNIT'
[Unit]
Description=NatWest SPA public proxy watchdog (probes nginx /__proxy_health)
After=nginx.service
Wants=nginx.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/natwest-spa-watchdog.sh
# Hard ceiling so a hung curl never piles up.
RuntimeMaxSec=15
# Minimal privileges: the script only reads localhost:80 and (rarely)
# invokes `systemctl restart nginx`; that systemctl call needs root.
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=/var/run /run /var/log
ProtectHome=true
PrivateTmp=true
UNIT

sudo tee /etc/systemd/system/natwest-spa-watchdog.timer >/dev/null <<'TIMER'
[Unit]
Description=NatWest SPA public proxy watchdog (30s cadence)

[Timer]
# Wait 60 s after boot before the first probe so nginx has time to come
# up, then run every 30 s. Persistent=true would replay missed runs on
# resume; we explicitly do NOT want that (a 5-min nap shouldn't queue 10
# restart attempts on wake).
OnBootSec=60s
OnUnitActiveSec=30s
AccuracySec=1s
Unit=natwest-spa-watchdog.service

[Install]
WantedBy=timers.target
TIMER

sudo systemctl daemon-reload
sudo systemctl enable --now natwest-spa-watchdog.timer

# Make sure nginx itself recovers automatically if it crashes outright.
# AL2023's default nginx unit has Restart=on-failure already, but we layer
# a small drop-in to bound the restart count + cooldown so we don't get a
# crash-loop log fire-hose when an upstream is permanently dead.
sudo mkdir -p /etc/systemd/system/nginx.service.d
sudo tee /etc/systemd/system/nginx.service.d/restart.conf >/dev/null <<'DROPIN'
[Service]
Restart=on-failure
RestartSec=5s
StartLimitBurst=10
StartLimitIntervalSec=600s
DROPIN
sudo systemctl daemon-reload
REMOTE

# --- 5. Smoke test ----------------------------------------------------------
if [[ "${SKIP_VERIFY:-0}" != "1" ]]; then
  log "verifying http://${SPLUNK_PUBLIC_IP}/__proxy_health ..."
  if ! curl -fsS -m 10 "http://${SPLUNK_PUBLIC_IP}/__proxy_health" | grep -q '^ok'; then
    fail "nginx /__proxy_health did not return ok - check SG and nginx error log"
  fi
  log "verifying http://${SPLUNK_PUBLIC_IP}/ ..."
  if ! curl -fsS -m 15 -o /dev/null -w 'http=%{http_code} ttfb=%{time_starttransfer}s\n' "http://${SPLUNK_PUBLIC_IP}/"; then
    fail "SPA root not reachable - workers may not allow tcp/${WEB_FRONTEND_NODE_PORT} from the Splunk EC2 SG"
  fi
fi

log "SPA reachable at: http://${SPLUNK_PUBLIC_IP}/"
log "  /api/* -> upstream natwest_api_gateway (NodePort ${API_GATEWAY_NODE_PORT})"
log "  /      -> upstream natwest_web_frontend (NodePort ${WEB_FRONTEND_NODE_PORT})"
log "Re-run this script after any EKS managed node-group roll to refresh upstream IPs."
