"""Synthetic banking audit / SPA auth / chaos audit emitter.

Writes structured JSON events to a dedicated audit log file that a
sidecar (`audit-tail`) reads and ships to Splunk Enterprise via the
container stdout pipeline. Per-container splunk.com/sourcetype and
splunk.com/index annotations on the audit-tail sidecar route those
events to ``index=nwpay_audit`` (sourcetypes: ``nwpay:payment_audit``,
``nwpay:auth``, ``nwpay:chaos``) without polluting the main service
log stream that goes to ``index=main``.

Why a separate file instead of stdout?
  * The Splunk OTel collector chart routes container logs by pod or
    per-container annotation, not by log content. Mixing audit events
    into the regular service stdout would force every record from that
    pod into the audit index. A dedicated file picked up by a small
    sidecar lets us route per-container.
  * The file is rotated by Python's logging.handlers.RotatingFileHandler
    so a long-running pod cannot fill the emptyDir.

Privacy / PII (codeguard-0-privacy-data-protection,
codeguard-0-logging "redact/tokenize secrets and sensitive fields"):
  * ``customer_id`` is HMAC-SHA256 tokenized with a server-side pepper
    (``AUDIT_PEPPER`` env, or read from ``AUDIT_PEPPER_PATH`` file -
    Kubernetes Secret mount).
  * Account numbers, names, emails, phone numbers MUST NOT be passed to
    these helpers - the demo's payment payload schema does not include
    them, and ``emit_payment_audit`` does not accept them either, so a
    code reviewer can audit by inspection.
  * The pepper, if present, never enters the log stream and never enters
    a span attribute. The redaction is one-way; the original customer id
    cannot be recovered from the indexed digest.
"""

from __future__ import annotations

import hmac
import json
import logging
import os
import sys
import threading
import time
import uuid
from hashlib import sha256
from logging.handlers import RotatingFileHandler
from typing import Any

# Defer the OpenTelemetry import so this module is testable without the
# heavy SDK installed (the unit test hashes a customer id and exercises
# the JSON serialisation - it should not require splunk-py-trace).
try:
    from opentelemetry import trace as _otel_trace  # type: ignore
except Exception:  # pragma: no cover - SDK absent in unit-test venv
    _otel_trace = None


# ---------------------------------------------------------------------------
# Configuration. Values are looked up once at import time so the runtime
# behaviour is deterministic across the lifetime of the process.
# ---------------------------------------------------------------------------

AUDIT_LOG_PATH = os.environ.get("AUDIT_LOG_PATH", "/var/log/audit/audit.jsonl")
AUDIT_LOG_MAX_BYTES = max(
    1024 * 1024, int(os.environ.get("AUDIT_LOG_MAX_BYTES", str(50 * 1024 * 1024)))
)
AUDIT_LOG_BACKUP_COUNT = max(
    0, int(os.environ.get("AUDIT_LOG_BACKUP_COUNT", "3"))
)

# AUDIT_ENABLED gates ALL emission. Defaults to true; per-pod values.yaml
# can flip this to false on services that should not emit audit events
# (e.g. low-tier infrastructure pods).
AUDIT_ENABLED = os.environ.get("AUDIT_ENABLED", "true").strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}

SERVICE_NAME = os.environ.get("OTEL_SERVICE_NAME", "unknown-service")
SERVICE_TIER = os.environ.get("SERVICE_TIER", "unknown")
DEPLOYMENT_ENVIRONMENT = os.environ.get("OTEL_RESOURCE_DEPLOYMENT_ENVIRONMENT", "demo")


def _load_pepper() -> bytes:
    """Resolve the HMAC pepper from env / file / fallback.

    Order of precedence:
      1. ``AUDIT_PEPPER_PATH`` - path to a Kubernetes Secret-mounted
         file. Preferred: the pepper never appears in the pod spec.
      2. ``AUDIT_PEPPER`` - environment variable (sensitive).
      3. Fallback: a deterministic per-pod value derived from
         ``HOSTNAME`` and a fixed salt. Logged at WARNING because this
         path is only safe for the demo and breaks redaction stability
         across pod restarts.

    Returns the pepper as bytes (UTF-8 encoded), or a generated bytes
    string for the fallback. Never returns an empty value: an empty
    pepper would silently degrade the HMAC into a known-construction
    SHA-256 prefix attack vector.
    """
    path = os.environ.get("AUDIT_PEPPER_PATH", "").strip()
    if path:
        try:
            with open(path, "rb") as f:
                data = f.read().strip()
            if data:
                return data
        except OSError as exc:  # noqa: BLE001
            logging.getLogger(SERVICE_NAME).warning(
                "audit_pepper_path_unreadable path=%s err=%s", path, exc
            )

    env = os.environ.get("AUDIT_PEPPER", "").strip()
    if env:
        return env.encode("utf-8")

    fallback = (
        f"audit-pepper-fallback:{os.environ.get('HOSTNAME', 'unknown-host')}"
    ).encode("utf-8")
    logging.getLogger(SERVICE_NAME).warning(
        "audit_pepper_fallback_in_use - configure AUDIT_PEPPER_PATH or AUDIT_PEPPER for stable redaction"
    )
    return fallback


_PEPPER: bytes = _load_pepper()


# ---------------------------------------------------------------------------
# Lazy file handler so unit tests that import this module do not fail when
# /var/log/audit does not exist.
# ---------------------------------------------------------------------------

_audit_handler_lock = threading.Lock()
_audit_handler: RotatingFileHandler | None = None
_fallback_to_stdout: bool = False


def _get_audit_handler() -> RotatingFileHandler | None:
    global _audit_handler, _fallback_to_stdout

    with _audit_handler_lock:
        if _audit_handler is not None or _fallback_to_stdout:
            return _audit_handler

        try:
            os.makedirs(os.path.dirname(AUDIT_LOG_PATH), exist_ok=True)
            handler = RotatingFileHandler(
                AUDIT_LOG_PATH,
                maxBytes=AUDIT_LOG_MAX_BYTES,
                backupCount=AUDIT_LOG_BACKUP_COUNT,
                encoding="utf-8",
                delay=True,
            )
            handler.setFormatter(logging.Formatter("%(message)s"))
            _audit_handler = handler
            return handler
        except OSError as exc:  # noqa: BLE001
            logging.getLogger(SERVICE_NAME).warning(
                "audit_log_unwritable path=%s err=%s - falling back to stdout",
                AUDIT_LOG_PATH,
                exc,
            )
            _fallback_to_stdout = True
            return None


def redact_customer_id(customer_id: str | None) -> str | None:
    """One-way HMAC tokenize a customer id with the configured pepper.

    Returns ``None`` if input is ``None`` or empty, otherwise a 32-char
    lowercase hex digest. ``hmac.compare_digest`` would be used for
    verification; this helper is for the emit-side only.

    The output is stable for the lifetime of a pepper. Rotating the
    pepper invalidates historical correlations - acceptable in a demo,
    documented in audit.py header for any prod adopter.
    """
    if customer_id is None:
        return None
    s = str(customer_id).strip()
    if not s:
        return None
    digest = hmac.new(_PEPPER, s.encode("utf-8"), sha256).hexdigest()
    return digest[:32]


def _current_trace_id() -> str | None:
    """Best-effort: pull the active OTel trace id so audit events can be
    pivoted to APM. Returns ``None`` when the SDK is absent or the span
    is not recording (e.g. background thread without context)."""
    if _otel_trace is None:
        return None
    try:
        span = _otel_trace.get_current_span()
        if span is None:
            return None
        ctx = span.get_span_context()
        if ctx is None or not ctx.is_valid:
            return None
        return format(ctx.trace_id, "032x")
    except Exception:  # noqa: BLE001
        return None


def _emit(payload: dict[str, Any]) -> None:
    """Serialize and ship one audit record.

    JSON dumped with ``separators=(",", ":")`` keeps the line compact;
    ``ensure_ascii=False`` preserves Unicode customer names without
    surrogate-pair escaping (these are still allow-listed by the caller
    via ``customer_tier`` / ``decline_reason`` enums).

    Any record whose body would exceed 4 KB is truncated and logged
    with ``"_truncated":true``; this is a defensive ceiling, the real
    payload schema below is well under 1 KB. Truncation prevents one
    misuse from pushing the audit pipeline into log injection territory
    (codeguard-0-logging).
    """
    if not AUDIT_ENABLED:
        return

    line = json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
    if len(line.encode("utf-8")) > 4096:
        # Drop unknown extras; keep core fields. Re-emit with a marker.
        compact = {
            k: payload.get(k)
            for k in (
                "@timestamp",
                "event_type",
                "service",
                "outcome",
                "trace_id",
            )
        }
        compact["_truncated"] = True
        line = json.dumps(compact, separators=(",", ":"), ensure_ascii=False)

    handler = _get_audit_handler()
    if handler is not None:
        try:
            handler.emit(logging.LogRecord(
                name="nwpay.audit",
                level=logging.INFO,
                pathname=__file__,
                lineno=0,
                msg=line,
                args=None,
                exc_info=None,
            ))
            return
        except Exception:  # noqa: BLE001 - never let audit failure crash the flow
            pass

    # Fallback: stdout. The collector pod-level annotation will route
    # this to the wrong index (main, not nwpay_audit), but at least the
    # event survives. Operations gets a loud warning at process start.
    sys.stdout.write(line + "\n")
    sys.stdout.flush()


# ---------------------------------------------------------------------------
# Public emitters.
# ---------------------------------------------------------------------------

# Whitelisted strings - any caller passing arbitrary text gets coerced
# back into the closed enum so a log-injection attempt cannot split a
# JSON record by injecting `"` or `\n` (escape=json on the emitter side
# also handles this, but defense in depth).
_KNOWN_TIERS = frozenset({"bronze", "silver", "gold"})
_KNOWN_DECISIONS = frozenset(
    {"accepted", "rejected", "throttled", "review", "error", "unknown"}
)
_KNOWN_DECLINE_REASONS = frozenset(
    {
        "",
        "tier_throttle",
        "fraud_score_high",
        "sanctions_match",
        "insufficient_funds",
        "limit_breach",
        "scheme_unavailable",
        "downstream_error",
        "simulated",
    }
)
_KNOWN_AUTH_OUTCOMES = frozenset(
    {"success", "failed", "logout", "session_expired", "rate_limited"}
)
# Network Information API effective_type closed enum. The W3C spec
# (https://wicg.github.io/netinfo/#dom-effectiveconnectiontype) defines
# exactly these values; everything else gets coerced to "unknown" so a
# malicious caller cannot smuggle arbitrary strings into the audit
# record (codeguard-0-input-validation-injection: positive validation
# at the trust boundary).
_KNOWN_NETWORK_TYPES = frozenset(
    {"slow-2g", "2g", "3g", "4g", "wifi", "ethernet", "unknown"}
)
# Source of the network beacon - "session_start" is fired once at
# initNetworkContext(), "change" on every connection.change callback.
_KNOWN_NETWORK_SOURCES = frozenset({"session_start", "change"})


def _coerce(value: Any, allowed: frozenset[str], default: str) -> str:
    if value is None:
        return default
    s = str(value).strip().lower()
    return s if s in allowed else default


def emit_payment_audit(
    payment_id: str,
    customer_id: str | None,
    customer_tier: str | None,
    scheme: str | None,
    amount_minor_units: int | float | None,
    currency: str | None,
    decision: str,
    decline_reason: str | None = None,
    sanctions_hit: bool = False,
    fraud_score: float | None = None,
    channel: str | None = None,
) -> None:
    """Emit one ``nwpay:payment_audit`` event."""
    payload: dict[str, Any] = {
        "@timestamp": time.strftime(
            "%Y-%m-%dT%H:%M:%S." + f"{int((time.time() % 1) * 1000):03d}Z",
            time.gmtime(),
        ),
        "event_type": "payment_audit",
        "service": SERVICE_NAME,
        "service_tier": SERVICE_TIER,
        "deployment_environment": DEPLOYMENT_ENVIRONMENT,
        "payment_id": str(payment_id),
        "customer_id_hash": redact_customer_id(customer_id),
        "customer_tier": _coerce(customer_tier, _KNOWN_TIERS, "bronze"),
        "scheme": (scheme or "").upper() or None,
        "amount_minor_units": int(amount_minor_units) if amount_minor_units is not None else None,
        "currency": (currency or None),
        "channel": channel or None,
        "decision": _coerce(decision, _KNOWN_DECISIONS, "unknown"),
        "decline_reason": _coerce(
            decline_reason or "", _KNOWN_DECLINE_REASONS, ""
        ) or None,
        "sanctions_hit": bool(sanctions_hit),
        "fraud_score": (
            round(max(0.0, min(1.0, float(fraud_score))), 4)
            if fraud_score is not None
            else None
        ),
        "trace_id": _current_trace_id(),
    }
    _emit({k: v for k, v in payload.items() if v is not None})


def emit_auth_event(
    username: str,
    outcome: str,
    client_ip: str | None = None,
    user_agent: str | None = None,
    mfa: bool = False,
) -> None:
    """Emit one ``nwpay:auth`` event for the SPA login/logout flow.

    Note that ``username`` is treated as a low-sensitivity identifier
    (the demo only has named personas: olivia/james/margaret/admin).
    For any production adoption, hash this the same way as customer_id.
    """
    payload: dict[str, Any] = {
        "@timestamp": time.strftime(
            "%Y-%m-%dT%H:%M:%S." + f"{int((time.time() % 1) * 1000):03d}Z",
            time.gmtime(),
        ),
        "event_type": "auth",
        "service": SERVICE_NAME,
        "service_tier": SERVICE_TIER,
        "deployment_environment": DEPLOYMENT_ENVIRONMENT,
        "username": str(username)[:64] if username else None,
        "outcome": _coerce(outcome, _KNOWN_AUTH_OUTCOMES, "failed"),
        "client_ip": (str(client_ip)[:64] if client_ip else None),
        "user_agent": (str(user_agent)[:256] if user_agent else None),
        "mfa": bool(mfa),
        "trace_id": _current_trace_id(),
    }
    _emit({k: v for k, v in payload.items() if v is not None})


def emit_network_event(
    session_id: str | None,
    customer_id: str | None,
    customer_tier: str | None,
    effective_type: str | None,
    previous_effective_type: str | None,
    downlink_mbps: float | None,
    rtt_ms: int | None,
    save_data: bool,
    source: str,
    client_ip: str | None = None,
    user_agent: str | None = None,
) -> None:
    """Emit one ``event_type=network`` audit event for SPA network state.

    Bridges the browser's view of the network (Network Information API)
    into Splunk Enterprise so ITSI correlation searches can fire on
    intermittent-connectivity signals - the equivalent data is in
    Splunk Observability Cloud (RUM) but not reachable from ITSI today.

    Schema (all closed enums / size caps applied):
      - session_id            opaque RUM session id (<=64 chars)
      - customer_id           HMAC-SHA256 hashed via redact_customer_id
      - customer_tier         coerced to bronze/silver/gold/unknown
      - effective_type        coerced via _KNOWN_NETWORK_TYPES
      - previous_effective_type  coerced via _KNOWN_NETWORK_TYPES
      - downlink_mbps         clamped to [0, 1000]
      - rtt_ms                clamped to [0, 60000]
      - save_data             bool
      - source                "session_start" or "change"
      - client_ip / user_agent  same handling as emit_auth_event

    Cardinality budget: 5 effective_type values * 6 (with from-state) *
    3 tiers ~= 90 distinct (customer_tier, from, to) tuples per source.
    Safe to leave running indefinitely.
    """
    payload: dict[str, Any] = {
        "@timestamp": time.strftime(
            "%Y-%m-%dT%H:%M:%S." + f"{int((time.time() % 1) * 1000):03d}Z",
            time.gmtime(),
        ),
        "event_type": "network",
        "service": SERVICE_NAME,
        "service_tier": SERVICE_TIER,
        "deployment_environment": DEPLOYMENT_ENVIRONMENT,
        "session_id": (str(session_id)[:64] if session_id else None),
        "customer_id_hash": redact_customer_id(customer_id),
        "customer_tier": _coerce(customer_tier, _KNOWN_TIERS, "bronze"),
        "effective_type": _coerce(effective_type, _KNOWN_NETWORK_TYPES, "unknown"),
        "previous_effective_type": (
            _coerce(previous_effective_type, _KNOWN_NETWORK_TYPES, "unknown")
            if previous_effective_type
            else None
        ),
        "downlink_mbps": (
            round(max(0.0, min(1000.0, float(downlink_mbps))), 3)
            if downlink_mbps is not None
            else None
        ),
        "rtt_ms": (
            int(max(0, min(60000, int(rtt_ms))))
            if rtt_ms is not None
            else None
        ),
        "save_data": bool(save_data),
        "source": _coerce(source, _KNOWN_NETWORK_SOURCES, "change"),
        "client_ip": (str(client_ip)[:64] if client_ip else None),
        "user_agent": (str(user_agent)[:256] if user_agent else None),
        "trace_id": _current_trace_id(),
    }
    _emit({k: v for k, v in payload.items() if v is not None})


# ---------------------------------------------------------------------------
# PSD2 Strong Customer Authentication (SCA) event emission.
#
# UK retail banks must produce regulator-ready audit trails for every
# SCA challenge: which method (SMS OTP, push notification, biometric,
# device-bound passkey, hardware token), which RTS exemption (if any),
# and which outcome (passed, failed, abandoned, expired). This helper
# emits the canonical record.
#
# All fields are server-coerced to fixed allow-lists so a malicious
# caller cannot widen the schema or smuggle PII.
# ---------------------------------------------------------------------------

# Closed enums per PSD2 RTS Article 4 (SCA elements) and Articles
# 10-18 (exemptions). Anything outside the list is normalised to a
# safe default; this prevents log-injection from exposing arbitrary
# strings to downstream queries.
_KNOWN_SCA_METHODS = frozenset({
    "sms_otp", "push_notification", "biometric_face",
    "biometric_fingerprint", "passkey", "hardware_token", "card_reader",
})
_KNOWN_SCA_OUTCOMES = frozenset({"passed", "failed", "abandoned", "expired", "challenged"})
_KNOWN_SCA_EXEMPTIONS = frozenset({
    "low_value",                   # RTS Art. 16
    "trusted_beneficiary",         # RTS Art. 13
    "recurring_payment",           # RTS Art. 14
    "corporate_payment",           # RTS Art. 17
    "transaction_risk_analysis",   # RTS Art. 18
    "contactless_low_value",       # RTS Art. 11
    "unattended_terminal",         # RTS Art. 12
})


def emit_sca_event(
    username: str,
    sca_method: str,
    sca_outcome: str,
    sca_exemption: str | None = None,
    challenge_id: str | None = None,
    payment_id: str | None = None,
    risk_score: float | None = None,
    duration_ms: int | None = None,
) -> None:
    """Emit one ``nwpay:auth event_type=sca_challenge`` record.

    Used by the SPA login + payment-initiation flows whenever PSD2
    Strong Customer Authentication is invoked. Closed enums on
    ``sca_method`` / ``sca_outcome`` / ``sca_exemption`` mean a hostile
    caller cannot inject arbitrary values into the regulatory audit
    trail (codeguard-0-input-validation-injection: positive allow-list
    validation at the trust boundary).
    """
    payload: dict[str, Any] = {
        "@timestamp": time.strftime(
            "%Y-%m-%dT%H:%M:%S." + f"{int((time.time() % 1) * 1000):03d}Z",
            time.gmtime(),
        ),
        "event_type": "sca_challenge",
        "service": SERVICE_NAME,
        "service_tier": SERVICE_TIER,
        "deployment_environment": DEPLOYMENT_ENVIRONMENT,
        "username": str(username)[:64] if username else None,
        "sca_method": _coerce(sca_method, _KNOWN_SCA_METHODS, "sms_otp"),
        "sca_outcome": _coerce(sca_outcome, _KNOWN_SCA_OUTCOMES, "failed"),
        # Exemption is optional. Only emit if explicitly invoked AND in
        # the allow-list; otherwise omit (None gets stripped below).
        "sca_exemption": (
            sca_exemption if sca_exemption in _KNOWN_SCA_EXEMPTIONS else None
        ),
        "challenge_id": str(challenge_id)[:64] if challenge_id else str(uuid.uuid4()),
        "payment_id": str(payment_id)[:64] if payment_id else None,
        "risk_score": (
            round(float(risk_score), 4)
            if risk_score is not None and 0.0 <= float(risk_score) <= 1.0
            else None
        ),
        "duration_ms": (
            int(duration_ms)
            if isinstance(duration_ms, int) and 0 <= duration_ms <= 600_000
            else None
        ),
        "trace_id": _current_trace_id(),
    }
    _emit({k: v for k, v in payload.items() if v is not None})


def emit_chaos_event(
    scenario: str,
    target_service: str | None,
    actor: str | None,
    action: str = "inject",
    started_at: float | None = None,
    ended_at: float | None = None,
    details: dict[str, Any] | None = None,
) -> None:
    """Emit one ``nwpay:chaos`` event from scripts/incident.sh.

    ``action`` is "inject" or "clear". The bash hook in
    ``scripts/incident.sh`` prefers a direct HEC POST, but this Python
    helper is provided for parity (and for a future Python-based chaos
    runner).
    """
    payload: dict[str, Any] = {
        "@timestamp": time.strftime(
            "%Y-%m-%dT%H:%M:%S." + f"{int((time.time() % 1) * 1000):03d}Z",
            time.gmtime(),
        ),
        "event_type": "chaos",
        "service": SERVICE_NAME,
        "scenario": str(scenario)[:64],
        "target_service": (str(target_service)[:64] if target_service else None),
        "actor": (str(actor)[:64] if actor else None),
        "action": "clear" if str(action).strip().lower() == "clear" else "inject",
        "started_at": started_at,
        "ended_at": ended_at,
        "event_id": str(uuid.uuid4()),
        "details": details if isinstance(details, dict) else None,
    }
    _emit({k: v for k, v in payload.items() if v is not None})
